version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: sever
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb+srv://truong18112002:<truong18112002>@mini-project.hiz1y8a.mongodb.net/

  frontend:
    build: client
    ports:
      - "3000:3000"
    depends_on:
      - backend
